name: Daily R devel build

on:
  schedule:
    - cron:  '30 14 * * *'

jobs:

  daily-r-devel:
    runs-on: ubuntu-latest
    env:
      R_VERSION: devel

    steps:

    - uses: actions/checkout@v1

    - name: Build the Docker image
      run: docker build --build-arg R_VERSION=${R_VERSION} -t docker.io/rhub/r-minimal:${R_VERSION} .

    - name: Log in to Docker Hub
      run: echo ${DOCKER_HUB_TOKEN} | docker login -u ${DOCKER_HUB_USERNAME} --password-stdin docker.io
      env:
        DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}

    - name: Log in to GitHub Packages
      run: echo ${GITHUB_TOKEN} | docker login -u ${GITHUB_USERNAME} --password-stdin docker.pkg.github.com
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}

    - name: Push it to Docker Hub, GitHub Packages
      run: |
        R_MAJOR=`echo ${R_VERSION} | sed 's/[.][0-9][0-9]*$//'`
        docker tag docker.io/rhub/r-minimal:${R_VERSION} docker.io/rhub/r-minimal:${R_MAJOR}
        docker tag docker.io/rhub/r-minimal:${R_VERSION} docker.pkg.github.com/r-hub/r-minimal/r-minimal:${R_VERSION}
        docker tag docker.io/rhub/r-minimal:${R_VERSION} docker.pkg.github.com/r-hub/r-minimal/r-minimal:${R_MAJOR}
        docker push docker.io/rhub/r-minimal:${R_VERSION}
        docker push docker.io/rhub/r-minimal:${R_MAJOR}
        docker push docker.pkg.github.com/r-hub/r-minimal/r-minimal:${R_VERSION}
        docker push docker.pkg.github.com/r-hub/r-minimal/r-minimal:${R_MAJOR}
        if [[ "$R_LATEST" == "$R_VERSION" ]]; then
          docker tag docker.io/rhub/r-minimal:${R_VERSION} docker.io/rhub/r-minimal:latest
          docker tag docker.io/rhub/r-minimal:${R_VERSION} docker.pkg.github.com/r-hub/r-minimal/r-minimal:latest
          docker push docker.io/rhub/r-minimal:latest
          docker push docker.pkg.github.com/r-hub/r-minimal/r-minimal:latest
        fi
